CREATE TABLE IF NOT EXISTS `anchor` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `level` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `fan` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `gender` VARCHAR(255) NULL,
  `birthday` VARCHAR(255) NULL,
  `zodiac` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tag` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `conversation` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `anchor_id` BIGINT NOT NULL,
  `fan_id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `fortune_service` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `input_schema` TEXT NULL,
  `created_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `fortune_record` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `fan_id` BIGINT NOT NULL,
  `service_id` BIGINT NOT NULL,
  `result` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `topic` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `popularity` INT NULL,
  `created_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `script` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `topic_id` BIGINT NULL,
  `created_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `workflow` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `definition` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `conversation` ADD CONSTRAINT `fk_conversation_anchor_id` FOREIGN KEY (`anchor_id`) REFERENCES `anchor`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `conversation` ADD CONSTRAINT `fk_conversation_fan_id` FOREIGN KEY (`fan_id`) REFERENCES `fan`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `fortune_record` ADD CONSTRAINT `fk_fortune_record_fan_id` FOREIGN KEY (`fan_id`) REFERENCES `fan`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `fortune_record` ADD CONSTRAINT `fk_fortune_record_service_id` FOREIGN KEY (`service_id`) REFERENCES `fortune_service`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `script` ADD CONSTRAINT `fk_script_topic_id` FOREIGN KEY (`topic_id`) REFERENCES `topic`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS `fan_tags` (
  `fan_id` BIGINT NOT NULL,
  `tag_id` BIGINT NOT NULL,
  PRIMARY KEY (`fan_id`, `tag_id`),
  CONSTRAINT `fk_fan_tags_fan` FOREIGN KEY (`fan_id`) REFERENCES `fan`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_fan_tags_tag` FOREIGN KEY (`tag_id`) REFERENCES `tag`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `conversation` (
  `anchor_id` BIGINT NOT NULL,
  `fan_id` BIGINT NOT NULL,
  PRIMARY KEY (`anchor_id`, `fan_id`),
  CONSTRAINT `fk_conversation_anchor` FOREIGN KEY (`anchor_id`) REFERENCES `anchor`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_conversation_fan` FOREIGN KEY (`fan_id`) REFERENCES `fan`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;