# DB Runner 配置模板（可选，ENV 优先生效）
# 用途：为 internal/ddl/runner.go 提供数据库连接与审批策略的参考模板。

dsn:
  # 示例：mysql://user:pass@tcp(127.0.0.1:3306)/xingzuo?parseTime=true&multiStatements=true
  test: ""
  staging: ""
  prod: ""

approval:
  approvers:
    - dba
    - tech-lead
  channels:
    read:
      requireTicket: false
    change:
      requireTicket: true
    rollback:
      requireTicket: true

window:
  # 操作超时（Go duration 格式）
  opTimeout: "30s"

audit:
  # 审计日志保留天数（仅文档约定，当前实现落盘 JSONL，不做自动清理）
  retentionDays: 90

conventions:
  softDelete: true
  softDeleteField: "deleted_at"
  indexPrefix: "idx_"
  uniquePrefix: "uniq_"